baseURL = 'https://dragonsnotincluded.github.io/'
DefaultContentLanguage = "en" # Theme's display language, supports: en, fr, zh, zh-hant
languageCode = 'en-gb'
title = 'Dragons Not Included'
copyright = "2020-2022, Dragons Not Included."
theme = ["hugo-theme-massively", "darths-hugo-shortcodes", "hugo-easy-gallery"]
# Disable errors in Hugo log for theme Massively
# disableKinds = [ "taxonomyTerm", "section"]
# ignore stupid error
ignoreErrors = ["error-missing-instagram-accesstoken", "error-remote-getjson", "error-disable-taxonomy"]
googleAnalytics = "G-G4GC4JMVVC"

# recommended for GitHub pages
publishDir = 'docs'

[markup.goldmark.renderer]
    unsafe = true

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "perldoc"
    tabWidth = 4

[params]
subtitle = "Themed by Diary."
enableGitalk = false
debug = true
CDNJS = false
paginate = 10

favicon = "/favicons/favicon.ico"
# This path doesn't like spaces on some systems:
backgroundPath = "/img/background.jpg"
enableAutoDarkMode=true

# Twitter Card and Open Graph settings
enableOpenGraph = true
enableTwitterCards = true
title = "Dragons Not Included" # will set 'og:site_name'
description = "Role-playing adventures in the Forgotten Realms"  # will set 'og:description'

# Tags
# default values
tagsDateFormat = "2006-01"
tagsShow = true
tagsCloudShow = true

[params.posts]
   folderName = "post"
   pageSize = "12"
   featuredPost = "true"

# [params.gitalk]
  # owner = "user"
  # repo = "repo name"
  # client_id = "your client id"  
  # client_secret = "your client secret"
[taxonomies]
   tag = "tags"
   category = "categories"
   author = "authors"

# [params.utterances]
# repo="your repo"
# term="[ENTER TERM HERE]"
# label="your label"
# theme="github-light"

# Legacy config from Hugo Theme Diary (https://github.com/AmazingRise/hugo-theme-diary)
# [[menu.main]]
# url = "/categories"
# name = "Adventures"
# weight = 2
# [[menu.main]]
# url = "/tags"
# name = "Characters"
# weight = 3
# [[menu.main]]
# url = "/posts"
# name = "Archive"
# weight = 1
# [[menu.main]]
# url = "/about"
# name = "About us"
# weight = 4
# [[menu.main]]
# url = "/index.xml"
# name = "RSS Feed"
# weight = 5
